### ISSUE TITLE
Update to AbstractMCMC v3

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/TuringCallbacks.jl#26]

**Comment by theogf** [comment]
The CompatHelper workflow just needed to be reenabled :)

**Comment by torfjelde** [comment]
No I mean e.g. https://github.com/TuringLang/TuringCallbacks.jl/blob/2f75e264841d718df6b8bad9ea41258bcfab4230/src/callbacks/tensorboard.jl#L112 no longer has the correct signature since we now need to include `state` and `; kwargs...` :)

**Comment by theogf** [comment]
EDIT: EDIT: EDIT: Ah yeah I guess I will have to do the same for Turkie.

But Turing/Dynamic has not updated to the new version yet right?

**Comment by torfjelde** [comment]
Closed by #27 thanks to @cpfiffer
